### ISSUE TITLE
How about supporting MCBE 1.17.10?

### ISSUE THREAD

**Issue by ghost** [bundabrg/Geyser#14]
### What feature do you want to see added?

support MCBE 1.17.10

### Are there any alternatives?

none

**Comment by DJelly4K** [comment]
Although it says that it supports 1.17.0~1.17.2, it will prompt when actually joining the game: the outdated Geyser agent, the version is still not 1.17.0

**Comment by bundabrg** [comment]
This belongs in https://github.com/Bundabrg/GeyserReversion/ and it is being worked on at the moment.
