### ISSUE TITLE
New Skins won't apply after join

### ISSUE THREAD

**Issue by WesleyVanNeck** [bundabrg/Geyser#6]
After I quit with my current skin and switch to a different skin it won't show the new skin to bedrock client and to other bedrock players latest of your fork

**Comment by bundabrg** [comment]
Is this when changing skins using bedrock itself? That won't work yet.

What should work is (for example) using SkinsRestorer, setting a skin (ie /skin bob) and then without the need to quit and rejoin the new skin is seen by all.

**Comment by WesleyVanNeck** [comment]
@bundabrg yes in bedrock it self

**Comment by WesleyVanNeck** [comment]
It's really strange because it apply the skin after 30 minutes

**Comment by bundabrg** [comment]
I think I've resolved this so please re-open if it still happens.
