### ISSUE TITLE
Custom Skulls of players in game don't load properly 

### ISSUE THREAD

**Issue by Hellohi3654** [bundabrg/Geyser#7]
The Fix Skin Caching Commit that adds 
# Specify how many days images will be cached to disk to save downloading them from the internet.
# A value of 0 is disabled. (Default: 0)
cache-images: 0
broken custom skull loading of a players skull when that player is in the game

**Comment by Hellohi3654** [comment]
https://cdn.discordapp.com/attachments/736221216037273610/744877539733929994/unknown.png
Image of issue

**Comment by Hellohi3654** [comment]
![image](https://user-images.githubusercontent.com/57390764/90611191-c5f6d780-e249-11ea-9e50-8d6d517ad1ff.png)
also here is another image

**Comment by bundabrg** [comment]
Thanks for reporting this. I'll try reproduce it reliably and see if I can fix it.

**Comment by Hellohi3654** [comment]
Cool thanks

**Comment by Hellohi3654** [comment]
it started happening when you did that fix skin caching commit

**Comment by bundabrg** [comment]
I'm still yet to reproduce this behaviour but obviously it is still happening. If there is a simple set of steps I can use that would be helpful (IE starting with a blank flat world and doing these steps reliably produces the error).

**Comment by Hellohi3654** [comment]
Join a flat world on your java account then do /linkaccount bedrock username and link your bedrock and java accounts
After that get the skull of your java account and place it down
which ever loads first is what is displayed for both
e.g if the skull loads first the player will appear as a skull
and if the player loads first then the skull will appear as a player

You can also make this glitch happen by join with both your bedrock and java account and simply placing down the skull of a Java player

**Comment by Camotoy** [comment]
Fixed locally, and PRing to BMan's branch.

**Comment by Hellohi3654** [comment]
Nice

**Comment by bundabrg** [comment]
Thanks guys, I'll close this in favour of that.
