### ISSUE TITLE
When you teleport chunks don't load

### ISSUE THREAD

**Issue by JH3Y50N** [bundabrg/Geyser#9]
**Describe the bug**
When you teleport to a long distance the chunk don't load, tested with cache-chunks false and true

**To Reproduce**
All you need is a teleport to long distance

**Expected behavior**

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/29031972/94972534-d6080500-04df-11eb-82b4-bbde4bb2ce57.png)

**Server Version**
![image](https://user-images.githubusercontent.com/29031972/94972552-e3bd8a80-04df-11eb-8020-62ac8c59e00d.png)

**Geyser Version**

This server is running Geyser version 1.2.0-SNAPSHOT (git-a6e8ce14d2a4899becc75fb8b5101f42c10a57e7-a6e8ce1) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

The standalone version lasted release

**Minecraft: Bedrock Edition Version**
Lasted stable build

**Additional Context**
https://dump.geysermc.org/0emDEGgOzRKHojJRqPf9wfg3JEZqojIa

**Comment by Hellohi3654** [comment]
Hey man I had the same issue 
it is a issue with heath123 move fixes which I have fixed in my fork of geyser

You can download geyser from my releases page:
https://github.com/Hellohi3654/Geyser/releases

My fork is pretty much the same as bundabrg's but I update it more regularly

**Comment by bundabrg** [comment]
Yeah I just do weekly updates or so. Out of interest sake @Hellohi3654 is the fix merged into heaths branch itself because if so I can close this now.

**Comment by Hellohi3654** [comment]
No still not merged yet

**Comment by Hellohi3654** [comment]
heath has fixed the issue on his branch

**Comment by Hellohi3654** [comment]
I think this issue can be closed
